
[build]
  command = "yarn build"
  publish = "build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "https://sane-studio.de/.well-known/matrix"
  to = "https://matrix.sane-studio.de/.well-known/matrix"
  status = 200
  force = true
