backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "geofences"
    label: "Geofences"
    label_singular: "Geofence" # Used in the UI, ie: "New Post"
    folder: "src/assets/content/geofences"
    create: true
    fields:
      - label: "Geofences"
        name: "geofences"
        widget: "list"
        field:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Coordinate", name: "coordinate", widget: "map" }
          - { label: "Radius", name: "radius", widget: "number" }
          - { label: "Publish Date", name: "date", widget: "datetime", required: false }
          - { label: "Image", name: "image", widget: "image", required: false }
          - { label: "File", name: "file", widget: "file", required: false }
          - { label: "Tags", name: "tags", widget: "string", required: false }
          - { label: "Author", name: "author", widget: "string", required: false }

